### PR TITLE
Remove browserify

### PR DESCRIPTION
**Pull request by job13er**

### CODE REVIEW

**Comment by sandersky** [comment]
:+1:

**Comment by sophypal** [comment]
👍

**Comment by job13er** [comment]
Oops, forgot to close this. I ended up just pushing a branch to this repo so we can install from that, might be easier to keep the fork up-to-date that way in case it's not fixed upstream

**Comment by sglanzer** [comment]
You'll PR back to the main project I assume?  If there is a delay in them accepting the PR we'll go update `snippet` on all of our component repos to point to this

**Comment by job13er** [comment]
I opened an issue, but I don't think my workaround is a good one. It's using bower. The proper fix would be to properly shim it probably.

**Pull request closed without merging**
